- name: import prompt
  ansible.builtin.import_role:
      name: common
      tasks_from: prompt

- name : install mongo
  ansible.builtin.dnf:
    name : mongodb-org
    state : present

- name : copy repo file
  ansible.builtin.template:
    src: mongo.repo
    dest : /etc/yum.repos.d/mongo.repo
    owner : github-runner

- name : change the host 
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'
    owner : github-runner

- name : restart systemd_service
  ansible.builtin.systemd_service:
    name : mongod
    state : restarted
    enabled : true
    daemon_reload: true