# - name: import prompt
#   ansible.builtin.import_role:
#       name: common
#       tasks_from: prompt

# - name: create new user,download and copy the repo file
#   ansible.builtin.import_role:
#       name: common
#       tasks_from: new_user
      
# - name: install nodejs
#   ansible.builtin.import_role:
#       name: common
#       tasks_from: nodejs
      
# - name: restart service
#   ansible.builtin.import_role:
#       name: common
#       tasks_from: service

- name: import docker install
  ansible.builtin.import_role:
      name: common
      tasks_from: docker

- name : run docker
  community.docker.docker_container:
    name: {{ component }}
    image: "public.ecr.aws/w8x4g9h7/roboshop-v3/{{ component }}"
    ports:
      - "80:80"
    env:
      MONGO: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-{{env}}/data/user:MONGO token={{token}} url=https://vault_p-internal.sdevops.shop:8200 validate_certs=false') }}"
      REDIS_URL: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-{{env}}/data/user:REDIS_URL token={{token}} url=https://vault_p-internal.sdevops.shop:8200 validate_certs=false') }}"
      MONGO_URL: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-{{env}}/data/user:MONGO_URL token={{token}} url=https://vault_p-internal.sdevops.shop:8200 validate_certs=false') }}"
