- name: import prompt
  ansible.builtin.import_role:
      name: common
      tasks_from: prompt

- name : copy the rabbitmq repo file 
  ansible.builtin.template:
    src : rabbitmq.repo
    dest: /etc/yum.repos.d/rabbitmq.repo

- name : install rabbitmq
  ansible.builtin.dnf :
    name : rabbitmq-server
    state : installed

- name: restart service
  ansible.builtin.import_role:
      name: common
      tasks_from: service

- name : set the password 
  ansible.builtin.shell : |
    rabbitmqctl add_user roboshop roboshop123
    rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"
