- name: import prompt
  ansible.builtin.import_role:
      name: common
      tasks_from: prompt

- name : copy the rabbitmq repo file 
  ansible.builtin.template:
    src : rabbitmq.repo
    dest: /etc/yum.repos.d/rabbitmq.repo

- name : install rabbitmq
  ansible.builtin.dnf :
    name : rabbitmq-server
    state : installed

- name : copy user service
  ansible.builtin.template:
    src: rabbitmq.repo
    dest: /etc/yum.repos.d/rabbitmq.repo
    
- name : restart systemd_service
  ansible.builtin.systemd_service:
    name :  rabbitmq-server
    state : restarted
    enabled : true
    daemon_reload: true

- name : set the password 
  ansible.builtin.shell : |
    rabbitmqctl add_user {{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-{{env}}/data/rabbitmq:ROOT_USER token={{token}} url=https://vault_p-internal.sdevops.shop:8200 validate_certs=false') }} {{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-{{env}}/data/rabbitmq:ROOT_PASSWORD token={{token}} url=https://vault_p-internal.sdevops.shop:8200 validate_certs=false') }}
    rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"
