- name: import prompt
  ansible.builtin.import_role:
      name: common
      tasks_from: prompt

- name : install mysql SERVER
  ansible.builtin.dnf :
    name : mysql-server
    state : installed

- name : restart systemd_service
  ansible.builtin.systemd_service:
    name :  mysqld
    state : restarted
    enabled : true
    daemon_reload: true

- name : set password
  ansible.builtin.shell : |
    mysql_secure_installation --set-root-pass {{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-{{env}}/data/mysql:ROOT_PASSWORD token={{token}} url=https://vault_p-internal.sdevops.shop:8200 validate_certs=false') }}