- name: import prompt
  ansible.builtin.import_role:
      name: common
      tasks_from: prompt

- name : install mysql SERVER
  ansible.builtin.dnf :
    name : mysql-server
    state : installed

- name: restart service
  ansible.builtin.import_role:
      name: common
      tasks_from: service

- name : set password
  ansible.builtin.shell : |
    mysql_secure_installation --set-root-pass RoboShop@1