- name : set prompt 
  ansible.builtin.import_role:
    name       : common
    tasks_from : prompt

- name: Download and add repo file 
  ansible.builtin.get_url:
    url: https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
    dest: /etc/yum.repos.d/hashicorp.repo
    mode: '0440'

- name : install vault 
  ansible.builtin.dnf:
    name : vault
    state : installed

- name : start service
  ansible.builtin.systemd_service : 
    name : vault
    state: restarted
    enabled: yes