- name: install golang
  ansible.builtin.dnf :
    name: golang
    state: installed

- name: building golang
  ansible.builtin.shell: |
    go mod init dispatch
    go get 
    go build
  args:
    chdir: /app