- name : install maven for java
  ansible.builtin.dnf:
    name : maven
    state : installed

- name: install dependencies and build maven
  ansible.builtin.shell: mvn clean package ; mv target/{{ component }}-1.0.jar {{ component }}.jar
  args:
    chdir: /app
  