- name : disable old node js 
  ansible.builtin.shell : dnf module disable nodejs -y

- name : enable nodejs 20
  ansible.builtin.shell : dnf module enable nodejs:20 -y

- name : install nodejs
  ansible.builtin.dnf:
    name : nodejs
    state : installed

- name : install npm dependencies
  ansible.builtin.shell : npm install
  args :
    chdir : /app