- name: install python 
  ansible.builtin.dnf:
    name:
      - python3 
      - gcc 
      - python3-devel 
    state: present

- name: build python 
  ansible.builtin.shell: pip3 install -r requirements.txt
  args:
    chdir: /app